server {
    listen 8080;
    server_name _;
    root /var/www/html;
    index index.php index.html;
    client_max_body_size 200m;

    location ^~ /files/ {
        deny all;
        return 404;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ ^(.+\.php)(.*)$ {
        fastcgi_split_path_info ^(.+\.php)(.*)$;
        set $saved_path_info $fastcgi_path_info;
        try_files $fastcgi_script_name =404;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $saved_path_info;
        fastcgi_param HTTPS on;
        fastcgi_param HTTP_X_FORWARDED_PROTO https;
        fastcgi_param SERVER_PORT 443;
        fastcgi_param REQUEST_SCHEME https;
        fastcgi_param SERVER_NAME $host;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_read_timeout 300s;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    location ~* ^/(config\.inc\.php|README|SECURITY|composer\.(json|lock))$ {
        deny all;
    }
}
